- name: Download node exporter
  ansible.builtin.get_url:
    url: https://github.com/prometheus/node_exporter/releases/download/v1.6.1/node_exporter-1.6.1.linux-amd64.tar.gz
    dest: /tmp/node-exporter.tar.gz

- name: Unarchive node exporter
  ansible.builtin.unarchive:
    src: /tmp/node-exporter.tar.gz
    dest: /tmp
    remote_src: yes

- name: Copy node exporter binary
  ansible.builtin.copy:
    src: /tmp/node_exporter-1.6.1.linux-amd64/node_exporter
    dest: /usr/local/bin
    remote_src: yes
    mode: '755'

- name: Template a file to /etc/systemd/system
  ansible.builtin.template:
    src: /home/ubuntu/ansible-prometheus-grafana/ansible/roles/node-exporter/templates/node_exporter.service.j2
    dest: /etc/systemd/system/node_exporter.service

- name: Make sure a service unit is running
  ansible.builtin.systemd:
    state: started
    name: node_exporter
    enabled: yes